// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xczbzmaujelxuxwaitkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjemJ6bWF1amVseHV4d2FpdGt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5OTQ2ODIsImV4cCI6MjA2MjU3MDY4Mn0.YQwRytOxxOvtlpkjki_3uinfXrty5AumHlUg9eTd9yA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);